### ISSUE TITLE
Problem to pull

### ISSUE THREAD

**Issue by Heziode** [nazar-pc/docker-webserver#12]
Hi, I've one problem when I want pull your Docker...

Message :
Using default tag: latest
Pulling repository docker.io/nazarpc/webserver
Tag latest not found in repository docker.io/nazarpc/webserver

**Comment by nazar-pc** [comment]
There is no tag `latest` there. Instead, different images have their own tags, like `nazarpc/webserver:nginx`.
You have to pull all of them separately (thankfully most of them have common base).
The simplest way to pull them is to create `docker-compose.yml` and then run `docker-compose pull`

**Comment by Heziode** [comment]
Oh yes, right !
Thank's for quick trply :)
