### ISSUE TITLE
Merge if statements

### ISSUE THREAD

**Issue by Lewiscowles1986** [nazar-pc/docker-webserver#14]
https://github.com/nazar-pc/docker-webserver/blob/master/ssh/webserver-entrypoint.sh#L15 for some reason it's repeating the last statement and only has one difference in the final line of the body of the if statement. Is there a reason for this, or was it just overlooked?

**Comment by Lewiscowles1986** [comment]
seen it, ssh & .ssh

**Comment by nazar-pc** [comment]
I'm not very experienced with Bash, feel free to open another issue if you find anything, there might be a way to make certain things nicer:)
