### ISSUE TITLE
help chapter in readme for rookie

### ISSUE THREAD

**Issue by PaulWeb** [nazar-pc/docker-webserver#17]
Could you add chapter in readme for rookie(dumb)? for example I have index.php file with phpinfo: what steps need to do to see it in  browser using your docker-webserver? because it is not clear, I created example.com, added yml, then run up -d and what next? 

According readme 

> Before you enter ssh container via SSH for the first time, you need to create file /data/.ssh/authorized_keys

where I have to create .ssh file inside example.com on host machine or inside docker-machine or container?

P.S: Thanks for repo

**Comment by nazar-pc** [comment]
Valid point. Feel free to PR if you get some content for readme, that you feel like it might be useful for others.

**Comment by nazar-pc** [comment]
I've added support for `PUBLIC_KEY` environment variable in SSH container image, should be much easier to get started now.
