### ISSUE TITLE
nginx + php-fpm = 502

### ISSUE THREAD

**Issue by antoinemineau** [nazar-pc/docker-webserver#18]
Hi,

Thanks for your great repository.
I am trying to use it for a php application, html pages runs fine but when I try to uncomment the php block of the default.conf in nginx

```
location ~ \.php$ {
    root           html;
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_index  index.php;
    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    include        fastcgi_params;
}
```

 I have the following error log :  

```
*6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: localhost:8000"
```

Any ideas ?

**Comment by nazar-pc** [comment]
You're trying to get PHP from `127.0.0.1:9000` while if you have `php` service in your `docker-compose.yml` you'll need to use `php:9000` instead.

**Comment by antoinemineau** [comment]
Thanks, it works with php:9000 👍 

I thought that the nginx default.conf would work without changes.

**Comment by nazar-pc** [comment]
Added small tweak in ba78597, should now work out of the box with default config
