### ISSUE TITLE
Data container volume issue

### ISSUE THREAD

**Issue by jaroslavlibal** [nazar-pc/docker-webserver#21]
Hello,

thanks for all the instructions.

I would like to ask you if you can help me with the issue:
`Service "data" mounts volumes from "example.com", which is not the name of a service or container.`

I have followed all your steps, but `docker compose up` ends up with the error message above.

Thanks in advance.

**Comment by jaroslavlibal** [comment]
Note: Issue relates to the yesterday's change to "version 2".

**Comment by nazar-pc** [comment]
Thanks for noticing this! I forgot to add this, it should be `container:example.com` in v2, should be good now.
