### ISSUE TITLE
git password for ssh container?

### ISSUE THREAD

**Issue by un-precedented** [nazar-pc/docker-webserver#27]
what's the default password for git user?

**Comment by nazar-pc** [comment]
There is no default password or key for security reasons. You can't enter until you provide your public key.

**Comment by un-precedented** [comment]
Well I added the public key of my local/remote machine in the SSH container, and it has been saved at the correct location. But I am not able to do FTP over SSH to the SSH container. I was able to login fine before the upgrade. Any ideas what's missing?

**Comment by nazar-pc** [comment]
If you've put `id_rsa.pub` contenst into `/data/.ssh/authorized_keys` file it should just work. Make sure you've exposed SSH port in SSH container and specified it during remote connection. Also try to SSH to it using terminal to get some more details about what is going on.

**Comment by un-precedented** [comment]
this is what happens when I do ssh using terminal. I entered nothing for passphrase and password.
Port 23 of my host is linked up with 22 of the SSH container.


Bs-MBP:~ user1$ ssh git@104.131.188.19 -p 23
Enter passphrase for key '/Users/user1/.ssh/id_rsa': 
git@104.131.188.19's password: 
Permission denied, please try again.
git@104.131.188.19's password: 
Permission denied, please try again.
git@104.131.188.19's password: 
Permission denied (publickey,password).

**Comment by nazar-pc** [comment]
Looks like your SSH key is not picked by SSH daemon.
Can you run `ls -al /data/.ssh`? Output should be like this (make sure user, group and permissions are the same if you've created file manually):
```
root@cc23bd63abe9:/# ls -al /data/.ssh
total 12
drwxr-xr-x 2 root root 4096 Mar 24 11:19 .
drwxr-xr-x 7 root root 4096 Mar 24 11:19 ..
-rw-r--r-- 1 root root  743 Mar 24 11:19 authorized_keys
```

**Comment by un-precedented** [comment]
well I tried with my password in the passphrase...and it worked. This is a pretty common password that I use in many places. So not sure what it means. My SFTP is still giving authentication error - it doesn't ask me for passphrase, otherwise I would give it one.

**Comment by nazar-pc** [comment]
Well, then the reason is that your `/Users/user1/.ssh/id_rsa` is not a plaintext private key, but rather an encrypted version of it (and it should be so).
Generally GUI you're using should ask for password (like your terminal) to decrypt private key when you try to use it.
What app are you using to connect to sftp? Did it work for you before?

This is NOT FTP, so if you're trying to connect to the server as to FTP it wouldn't work, try SSH connection option if your GUI have that.

**Comment by un-precedented** [comment]
Makes sense. Well, I am using FileZilla. I choose SFTP as the protocol, which is SSH file tranfer protocol.
Somehow I had made it work before the upgrade, and it was working for a long time. So I don't remember if I did any special setting the first time.

**Comment by un-precedented** [comment]
I got the filezilla working.

There was a logon type of "key file", and I specified my local machine's private key file in it. Now it asks me the paraphrase, and then successfully gets me in.

**Comment by un-precedented** [comment]
I still wonder how it was working without this before the upgrade...

**Comment by nazar-pc** [comment]
Glad to know it works now. Can you close issues that were already solved?
