### ISSUE TITLE
No option for php5?

### ISSUE THREAD

**Issue by kolayuk** [nazar-pc/docker-webserver#28]

**Comment by nazar-pc** [comment]
PHP 5.6 receives security fixes only and is not actively supported, thus will never be added here.
This repository will always suport either last of pre-last actively supported PHP version like it is now.

However, if you need PHP 5.6 for some reason you can have it, just like you can have any other language like Python or JavaScript. In case of PHP 5.6 take a look at corresponding [Dockerfile](https://github.com/nazar-pc/docker-webserver/blob/master/Dockerfile-php-fpm) and [its base](https://github.com/nazar-pc/docker-php/blob/master/fpm/Dockerfile). If you tweak those for PHP 5.6 it will be running just fine, but maintaining obtained image will be on you.
