### ISSUE TITLE
Why you use data-container instead data named volumes?

### ISSUE THREAD

**Issue by kksudo** [nazar-pc/docker-webserver#29]

**Comment by nazar-pc** [comment]
First of all I was using it before named volumes were introduces in Docker I think (thus I was able to able to upgrade my own installations).
Also in my opinion it is easier to manage in this way - less words, previous versions had much more volumes and it would have being very verbose to declare them all separately as well as would complicate upgrade (and backup/restore data too).

Having that said, there is nothing that prevents you from using named volumes, it will work perfectly fine if you prefer to do so.
