### ISSUE TITLE
A few informative questions (limitation resusrs && ui for containers )

### ISSUE THREAD

**Issue by kksudo** [nazar-pc/docker-webserver#30]
- You use limitation containers via docker-compose ( i have some problem this in vps ) ?
- You use any UI panel for monitoring health containers, for control containers ( something like [proxmox ](https://upload.wikimedia.org/wikipedia/commons/f/f6/Proxmox-VE-4-4-screenshot-startpage.png) )?
- You use you own repo for production ready ?

**Comment by nazar-pc** [comment]
> You use limitation containers via docker-compose ( i have some problem this in vps ) ?

No, didn't really need to yet

> You use any UI panel for monitoring health containers, for control containers ( something like proxmox )?

No, again, I don't need to. I've experimented with Rancher in its early days, but ended up creating subdirectories in `/root` with `docker-compose.yml` and supplementary files and I don't use any UI for managing containers. But you can take a look at Rancher and Rancher OS if you are interested, they are pretty cool.

> You use you own repo for production ready ?

I've deployed and updated it successfully many times on physical servers, Digital Ocean's instances and AWS EC2 instances - works fine everywhere and there are no known issues with it as of right now. So yes, I consider it production ready, however, I'm not aware how many people besides me are actually running it in production (there are 50k+ pulls in Docker Hub, but I have no idea how well it represents real-world usage).
