### ISSUE TITLE
nginx+PHP-FPM

### ISSUE THREAD

**Issue by nemozar** [nazar-pc/docker-webserver#31]
my nginx config 

`

    location / {
        root   /data/nginx/www;
        index  index.html index.htm;
    }
    location ~ \.php$ {
	root /data/nginx/www;
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        include        fastcgi_params;
    }

`

but when open localhost/1.php in response return "File not found."

in log nginx write "php_1         | 172.19.0.7 -  07/Jun/2017:07:39:58 +0000 "GET /1.php" 404"

how config PHP in NGINX? or how i can config with Apache form PHP (in phpMyAdmin used Apache for PHP?)

**Comment by nazar-pc** [comment]
phpMyAdmin is self-container, so despite it uses Apache, it is irrelevant here.

From the log it seems like you don't have `1.php` file in there. I'm wondering why did you put `root /data/nginx/www;` in each location instead of directly under `server`.

You can try to see if the file is there by entering Nginx container and examining contents:
```
docker-compose exec nginx ls -al /data/nginx/www
```

**Comment by nemozar** [comment]
docker-compose exec nginx ls -al /data/nginx/www

> drwxr-xr-x 2 git  git  4096 Jun  7 06:56 .
> drwxr-xr-x 5 git  git  4096 Jun  7 06:00 ..
> -rw-r--r-- 1 git  git     5 Jun  7 06:02 1.html
> -rw-r--r-- 1 git  git    12 Jun  7 06:37 2.php
> -rw-r--r-- 1 root root   90 Jun  7 06:00 index.html

in default config root set in each location.

1.html is well opened

**Comment by nazar-pc** [comment]
Since files are in place and permissions are correctly it is purely Nginx configuration issue.
Did you restart Nginx after changing its configuration?

**Comment by nazar-pc** [comment]
Wait, you have `1.html`, but not `1.php`

**Comment by nemozar** [comment]
>  Did you restart Nginx after changing its configuration?

i will stop docker-compose and `docker-compose up` after. if i comment `location ~ \.php$ {` then php file open for download.

`Wait, you have 1.html, but not 1.php` it is test. for all *.php files i get error. How for exists or not exists in server.

**Comment by nemozar** [comment]
```
server {
    listen       80;
    server_name  localhost;
    root   /data/nginx/www;
    location / {
        index  index.html index.htm;
    }
    location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        include        fastcgi_params;
    }
}
```

current config

**Comment by nazar-pc** [comment]
Can you post what is in logs when you try existing file, say, `2.php`?
Because `php_1 | 172.19.0.7 - 07/Jun/2017:07:39:58 +0000 "GET /1.php" 404` is actually correct answer for file that indeed doesn't exist.

You don't necessarily need to restart everything, you can just `docker-compose restart nginx`, since some other services like database might take longer and you shouldn't really wait for them as configuration is the same.

**Comment by nemozar** [comment]
```
drwxr-xr-x 2 git  git  4096 Jun  7 10:39 .
drwxr-xr-x 5 git  git  4096 Jun  7 06:00 ..
-rw-r--r-- 1 git  git     5 Jun  7 06:02 1.html
-rw-r--r-- 1 git  git     6 Jun  7 10:39 2.php
-rw-r--r-- 1 root root   90 Jun  7 06:00 index.html
-rw-r--r-- 1 git  git    12 Jun  7 06:37 index.php
```

```
php_1         | 172.19.0.7 -  07/Jun/2017:11:23:43 +0000 "GET /1.php" 404
php_1         | 172.19.0.7 -  07/Jun/2017:11:23:44 +0000 "GET /1.php" 404
php_1         | 172.19.0.7 -  07/Jun/2017:11:23:44 +0000 "GET /1.php" 404
php_1         | 172.19.0.7 -  07/Jun/2017:11:24:04 +0000 "GET /2.php" 404
```

when run `docker-compose restart nginx`
```
nginx_1       | 2017/06/07 06:31:48 [emerg] 1#1: unknown directive "﻿server" in /data/nginx/config/conf.d/default.conf:1
nginx_1       | nginx: [emerg] unknown directive "﻿server" in /data/nginx/config/conf.d/default.conf:1
```

config 

```
server {
    listen       80;
    server_name  localhost;
    root   /data/nginx/www;
    location / {
        index  index.html index.htm;
    }
    location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        include        fastcgi_params;
    }
}
```

**Comment by nazar-pc** [comment]
Take a look at answers in following SO question: https://stackoverflow.com/questions/19165976/nginx-emerg-unknown-directive-in-etc-nginx-sites-enabled-example-com3

**Comment by nazar-pc** [comment]
Did you change anything in `/data/nginx/config/nginx.conf`? `[emerg] unknown directive "﻿server"` doesn't make any sense.

**Comment by nemozar** [comment]
not problem with EOL. if i comment block with php and restart nginx file *.php dowloaded (config file is well)

in file `/data/nginx/config/nginx.conf` i set new config 

```
server {
	listen       80;
	server_name  localhost;
	root   /data/nginx/www;
	location / {
		index  index.html index.htm;
	}
	location ~ \.php$ {
		fastcgi_pass   php:9000;
		fastcgi_index  index.php;
		fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
		include        fastcgi_params;
	}
}
```


in error.log nginx

`2017/06/07 12:02:11 [error] 10#10: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET /2.php HTTP/1.1", upstream: "fastcgi://172.19.0.6:9000", host: "localhost:81"`

**Comment by nazar-pc** [comment]
This is not a correct config if you put virtual host right into `/data/nginx/config/nginx.conf` (see https://stackoverflow.com/questions/10934705/unknown-directive-server-in-etc-nginx-nginx-conf4)

What I'd suggest you to do is to restore original `/data/nginx/config/nginx.conf` from `/etc/nginx_dist/nginx.conf` and put your virtual host into `/data/nginx/config/conf.d/default.conf`. If should work this way.

**Comment by nemozar** [comment]
problem in line `fastcgi_param`

with `fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;` work good.

in default config after pull line `fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;`

**Comment by nazar-pc** [comment]
I do not change that particular line, it comes from base image. I typically replace the whole virtual host file with my own.

**Comment by nemozar** [comment]
Help me with php extension. How i understand me need instal in `nazarpc/php:fpm` container? but when i open him with exec bash and write apt-get install php-pgsql get error "Unable to locate package php-pgsql"

**Comment by nazar-pc** [comment]
This is a separate question and you should better ask it in separate issue so that it would be possible to to find it for other people.
The question about installing additional extensions was already asked here: https://github.com/nazar-pc/docker-webserver/issues/20
