### ISSUE TITLE
Сan not connect to my DB via phpmyadmin

### ISSUE THREAD

**Issue by kksudo** [nazar-pc/docker-webserver#34]
After last update containers ( today ) i can not connect to my DB via phpmyadmin docker, i see error: 

>  mysqli_real_connect(): (HY000/2002): Connection timed out

What's the problem, do you think?

I configured containers via docker-compose, i' am try force-recrate, i see error in docker, but i don't now what is problem ...

**Comment by nazar-pc** [comment]
There is something wrong with your setup. I've just updated my system to latest versions of all containers as of now and PhpMyAdmin connects to DB without issues.
There is no need to force-create anything, just `docker-compose pull && docker-compose up -d` and you're on latest versions of everything.

I have no idea what exactly is going on without additional information about your `docker-compose.yml` config and whether you did any manual tweaks inside. Try to examine logs with `docker-compose logs`.

**Comment by kksudo** [comment]
Hi!
problem was with ufw. I did proxy via nginx and open port in uwf, phpmyadmin - was open interface, but authorization return error. I'll try later to localize the error ......

**Comment by kksudo** [comment]
Hi again.
I found problem. Trouble was with docker [`--iptables=false`](https://github.com/moby/moby/issues/28241)

**Comment by nazar-pc** [comment]
Closing then as this is not docker-webserver's issue, but rather an upstream one.
